[project]
name = "aleefy_pets"
version = "0.1.0"
dependencies = [
    "flet>=0.85.0",
    "fpdf2",
    "arabic_reshaper",
    "python-bidi",
    "flet-printing"
]

[tool.flet]
product_name = "Aleefy Pets"
[tool.flet.android]
dependencies = ["pyjnius"]
exclude = ["flet_printing"]
[tool.flet.android.permission]
"android.permission.INTERNET" = true
"android.permission.READ_EXTERNAL_STORAGE" = true
"android.permission.WRITE_EXTERNAL_STORAGE" = true
